pipeline {
    agent any
    stages {
        stage ('Build') {
            steps {
                echo 'clone repo'
                sh '
                    git clone https://github.com/tiana480/Jenkins-ansible.git
                '
                sh 'ls'
            }
        }
    }
}